// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package summary

import "encoding/json"
import "fmt"
import "regexp"

// JSON schema for validating semantic version strings according to semver 2.0.0
// specification
type SemVer string

// UnmarshalJSON implements json.Unmarshaler.
func (j *SemVer) UnmarshalJSON(value []byte) error {
	type Plain SemVer
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`)
	}
	if len(plain) < 5 {
		return fmt.Errorf("field %s length: must be >= %d", "", 5)
	}
	if len(plain) > 256 {
		return fmt.Errorf("field %s length: must be <= %d", "", 256)
	}
	*j = SemVer(plain)
	return nil
}
