// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package summary

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "time"

// Base properties for all metrics
type Common struct {
	// The type of data the metric contains
	Contains CommonContains `json:"contains" yaml:"contains" mapstructure:"contains"`

	// The metric name
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The metric type
	Type CommonType `json:"type" yaml:"type" mapstructure:"type"`
}

type CommonContains string

const CommonContainsData CommonContains = "data"
const CommonContainsDefault CommonContains = "default"
const CommonContainsTime CommonContains = "time"

var enumValues_CommonContains = []interface{}{
	"default",
	"time",
	"data",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CommonContains) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CommonContains {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CommonContains, v)
	}
	*j = CommonContains(v)
	return nil
}

type CommonType string

const CommonTypeCounter CommonType = "counter"
const CommonTypeGauge CommonType = "gauge"
const CommonTypeRate CommonType = "rate"
const CommonTypeTrend CommonType = "trend"

var enumValues_CommonType = []interface{}{
	"counter",
	"gauge",
	"rate",
	"trend",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CommonType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CommonType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CommonType, v)
	}
	*j = CommonType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Common) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["contains"]; raw != nil && !ok {
		return fmt.Errorf("field contains in Common: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Common: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Common: required")
	}
	type Plain Common
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Common(plain)
	return nil
}

type Counter interface{}

type Gauge interface{}

type Rate interface{}

// JSON schema for validating semantic version strings according to semver 2.0.0
// specification
type Schema string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Schema) UnmarshalJSON(value []byte) error {
	type Plain Schema
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`)
	}
	if len(plain) < 5 {
		return fmt.Errorf("field %s length: must be >= %d", "", 5)
	}
	if len(plain) > 256 {
		return fmt.Errorf("field %s length: must be <= %d", "", 256)
	}
	*j = Schema(plain)
	return nil
}

// Official JSON schema for k6's machine-readable end-of-test summary format
// version 1.0
type Summary struct {
	// Configuration information about the test execution
	Config SummaryConfig `json:"config" yaml:"config" mapstructure:"config"`

	// Metadata about the summary generation
	Metadata SummaryMetadata `json:"metadata" yaml:"metadata" mapstructure:"metadata"`

	// Test execution results data
	Results SummaryResults `json:"results" yaml:"results" mapstructure:"results"`

	// Schema version in semver 2.0 format (e.g., '1.0.0')
	Version Schema `json:"version" yaml:"version" mapstructure:"version"`
}

// Configuration information about the test execution
type SummaryConfig struct {
	// Test run duration in seconds
	Duration float64 `json:"duration" yaml:"duration" mapstructure:"duration"`

	// Type of execution (local or cloud)
	Execution SummaryConfigExecution `json:"execution" yaml:"execution" mapstructure:"execution"`

	// Path or name of the test script
	Script *string `json:"script,omitempty" yaml:"script,omitempty" mapstructure:"script,omitempty"`
}

type SummaryConfigExecution string

const SummaryConfigExecutionCloud SummaryConfigExecution = "cloud"
const SummaryConfigExecutionLocal SummaryConfigExecution = "local"

var enumValues_SummaryConfigExecution = []interface{}{
	"local",
	"cloud",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SummaryConfigExecution) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SummaryConfigExecution {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SummaryConfigExecution, v)
	}
	*j = SummaryConfigExecution(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SummaryConfig) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["duration"]; raw != nil && !ok {
		return fmt.Errorf("field duration in SummaryConfig: required")
	}
	if _, ok := raw["execution"]; raw != nil && !ok {
		return fmt.Errorf("field execution in SummaryConfig: required")
	}
	type Plain SummaryConfig
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Duration {
		return fmt.Errorf("field %s: must be >= %v", "duration", 0)
	}
	*j = SummaryConfig(plain)
	return nil
}

// Metadata about the summary generation
type SummaryMetadata struct {
	// RFC3339 timestamp when summary was generated
	GeneratedAt time.Time `json:"generatedAt" yaml:"generatedAt" mapstructure:"generatedAt"`

	// Version of k6 that generated this summary
	K6Version Schema `json:"k6Version" yaml:"k6Version" mapstructure:"k6Version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SummaryMetadata) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["generatedAt"]; raw != nil && !ok {
		return fmt.Errorf("field generatedAt in SummaryMetadata: required")
	}
	if _, ok := raw["k6Version"]; raw != nil && !ok {
		return fmt.Errorf("field k6Version in SummaryMetadata: required")
	}
	type Plain SummaryMetadata
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SummaryMetadata(plain)
	return nil
}

// Test execution results data
type SummaryResults struct {
	// Check execution results
	Checks *SummaryResultsChecks `json:"checks,omitempty" yaml:"checks,omitempty" mapstructure:"checks,omitempty"`

	// Array of all metrics from the test execution
	Metrics []map[string]interface{} `json:"metrics" yaml:"metrics" mapstructure:"metrics"`

	// Whether the test passed (true) or failed (false). Determined by threshold
	// evaluations and other test criteria.
	Passed bool `json:"passed" yaml:"passed" mapstructure:"passed"`
}

// Check execution results
type SummaryResultsChecks struct {
	// Array of check-related metrics
	Metrics []map[string]interface{} `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Individual check results in execution order
	Results []SummaryResultsChecksResultsElem `json:"results,omitempty" yaml:"results,omitempty" mapstructure:"results,omitempty"`
}

type SummaryResultsChecksResultsElem struct {
	// Number of times the check failed
	Fails int `json:"fails" yaml:"fails" mapstructure:"fails"`

	// Check name
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Number of times the check passed
	Passes int `json:"passes" yaml:"passes" mapstructure:"passes"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SummaryResultsChecksResultsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["fails"]; raw != nil && !ok {
		return fmt.Errorf("field fails in SummaryResultsChecksResultsElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in SummaryResultsChecksResultsElem: required")
	}
	if _, ok := raw["passes"]; raw != nil && !ok {
		return fmt.Errorf("field passes in SummaryResultsChecksResultsElem: required")
	}
	type Plain SummaryResultsChecksResultsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Fails {
		return fmt.Errorf("field %s: must be >= %v", "fails", 0)
	}
	if 0 > plain.Passes {
		return fmt.Errorf("field %s: must be >= %v", "passes", 0)
	}
	*j = SummaryResultsChecksResultsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SummaryResults) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["metrics"]; raw != nil && !ok {
		return fmt.Errorf("field metrics in SummaryResults: required")
	}
	if _, ok := raw["passed"]; raw != nil && !ok {
		return fmt.Errorf("field passed in SummaryResults: required")
	}
	type Plain SummaryResults
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SummaryResults(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Summary) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["config"]; raw != nil && !ok {
		return fmt.Errorf("field config in Summary: required")
	}
	if _, ok := raw["metadata"]; raw != nil && !ok {
		return fmt.Errorf("field metadata in Summary: required")
	}
	if _, ok := raw["results"]; raw != nil && !ok {
		return fmt.Errorf("field results in Summary: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in Summary: required")
	}
	type Plain Summary
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Summary(plain)
	return nil
}

type Trend interface{}
