name: Validate JSON Schema and Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    name: Validate Schema and Examples
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        
      - name: Install JSON Schema CLI
        uses: sourcemeta/jsonschema@a1c61a0e66ee454b0ee71270124574862977c511 # v10.0.0
          
      - name: Validate JSON Schema 
        run: make validate-schema

      - name: Validate Examples
        run: make validate-examples